name: dashboard_reborn
description: A very sexy Flutter template!
version: 1.1.1+5

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  easy_dynamic_theme: ^2.2.0
  eva_icons_flutter: ^3.0.0
  flare_flutter: ^3.0.0
  gradient_widgets: ^0.6.0
  liquid_swipe: ^2.1.0
  url_launcher: ^5.5.0

dev_dependencies:
  flutter_launcher_icons: ^0.9.0

flutter_icons:
  android: 'launcher_icon'
  image_path_android: 'assets/icon/icon-legacy.png'
  adaptive_icon_foreground: 'assets/icon/icon-adaptive.png'
  adaptive_icon_background: '#fafafa'

  ios: true
  image_path_ios: 'assets/icon/icon-ios.png'

flutter:
  uses-material-design: true

  assets:
     - assets/credits/
     - assets/flare/
     - assets/icon/
     - assets/music/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/Rubik/Rubik-Regular.ttf
        - asset: assets/fonts/Rubik/Rubik-Medium.ttf
        - asset: assets/fonts/Rubik/Rubik-Bold.ttf
        - asset: assets/fonts/Rubik/Rubik-Italic.ttf
          style: italic

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono/RobotoMono-Regular.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Medium.ttf
        - asset: assets/fonts/RobotoMono/RobotoMono-Bold.ttf

    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
